<div>
    {% if not is_index %}
        <div style="text-align:center;color: #636363;font-size:14px;letter-spacing: 10px">本文结束啦<i class="fa fa-bell"></i>感谢您的阅读</div>
    {% endif %}
</div>
<br/>
<div style="border: 1px solid black ;text-align :center">
<div style="margin-top:10px">
<span style="font-weight:blod">版权声明</span>
<img src="http://7xqmjb.com1.z0.glb.clouddn.com/2017020242973cc.png" >
<br/>
<p style="font-size: 10px;line-height: 30px"><a href="http://tc9011.com" style="color:#258FC6">Aurora's Notes</a> by <a href="http://cherubic.top" style="color:#258FC6">Xiao Peng</a> is licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" style="color:#258FC6">Creative Commons BY-NC-ND 4.0 International License</a>.<br/>
由<a href="http://cherubic.top" style="color:#258FC6">筱鹏</a>创作并维护的<a href="http://cherubic.top" style="color:#258FC6">Aurora's Notes</a>博客采用<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" style="color:#258FC6">创作共用保留署名-非商业-禁止演绎4.0国际许可证</a>。<br/>
本文首发于<a href="http://tc9011.com" style="color:#258FC6">Aurora's Notes</a> 博客（ <a href="http://cherubic.top" style="color:#258FC6">http://cherubic.top</a> ），版权所有，侵权必究。</p>
</div>
</div>
